# Generated by Django 5.2.7 on 2025-10-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=10, null=True),
        ),
    ]
