# Generated by Django 4.2 on 2025-10-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_alter_media_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='analysis_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='media',
            name='audio_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='media',
            name='emotions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='media',
            name='faces_detected',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='media',
            name='objects_detected',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='media',
            name='scene_context',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Vidéo'), ('audio', 'Audio')], max_length=10, null=True),
        ),
    ]
